import React from "react";
import { BrowserRouter, Routes, Route } from 'react-router-dom';

import HomePage from "../pages/HomePage";
import RegisterPage from "../pages/RegisterPage";
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< master
import CreateQuestion from "../pages/CreateQuestion";
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
import LoginPage from "../pages/LoginPage";
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Fifo_to_ide_rozbit


import { Layout } from "../components/main/layout";

const AppRouter = () => {

    return (
        <BrowserRouter>
            <Layout>
                <Routes>
                    <Route path="/" element={<HomePage />} />
                    <Route path="/register" element={<RegisterPage />} />
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< master
                    <Route path="/createQuestion" element={<CreateQuestion />} />
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
                    <Route path="/login" element={<LoginPage />} />
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Fifo_to_ide_rozbit
                </Routes>
            </Layout>
        </BrowserRouter>
    )
}

export default AppRouter;